os: Visual Studio 2015

environment:
  nodejs_version: '8.11'
  matrix:
  - node_installer: npm

cache:
  - .eslintcache
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn'

branches:
  only:
    - auto-updater
    - /^release-.*/

version: '{build}'

install:
  - cmd: regedit /s script\default-to-tls12-on-appveyor.reg
  - git submodule update --init --recursive
  - npm install --prune

# test_script:
#   - npm run test

deploy_script:
  - npm run publish
