os: Visual Studio 2015

environment:
  nodejs_version: '8.11'
  matrix:
  - node_installer: npm
  GITHUB_TOKEN:
    secure: Ny4K0l6RB6+fckzK0mgIzafemr4hwDnuNmwXK3XI/hw6HC1nGbRYtdKbqWyPVLq6

cache:
  - .eslintcache
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn'

branches:
  only:
    - auto-updater
    - /^v[0-9].[0-9].?[0-9]?-?.*/

version: '{build}'

install:
  - cmd: regedit /s script\default-to-tls12-on-appveyor.reg
  - git submodule update --init --recursive
  - npm install --prune

# test_script:
#   - npm run test

deploy_script:
  - npm run publish
