os: Visual Studio 2015

environment:
  nodejs_version: '8.11'
  matrix:
  - node_installer: npm

cache:
  - .eslintcache
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn'

branches:
  only:
    - master
    - /^v[0-9].[0-9].?[0-9]?-?.*/

version: '{build}'

install:
  - cmd: regedit /s script\default-to-tls12-on-appveyor.reg
  - git submodule update --init --recursive
  - npm install --prune

build_script:
  - npm run make

artifacts:
  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'

# test_script:
#   - npm run test

deploy:
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: Ny4K0l6RB6+fckzK0mgIzafemr4hwDnuNmwXK3XI/hw6HC1nGbRYtdKbqWyPVLq6 # your encrypted token from GitHub
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: true
  on:
    branch: /^v[0-9].[0-9].?[0-9]?-?.*/  # release from tags only
    appveyor_repo_tag: true              # deploy on tag push only