notifications:
  email: false

dist: trusty

sudo: false

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
    - os: osx

language: node_js
node_js:
  - "8.11.3"


# this ensures PRs based on a local branch are not built twice
# the downside is that a PR targeting a different branch is not built
# but as a workaround you can add the branch to this list
branches:
  only:
    - master
    - /^__release-.*/

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - gnome-keyring
      - libsecret-1-dev
      - python-gnomekeyring

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval $(echo -n "" | /usr/bin/gnome-keyring-daemon --login); fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval $(/usr/bin/gnome-keyring-daemon --components=secrets --start); fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      dbus-launch /usr/bin/python -c \
        "import gnomekeyring;gnomekeyring.create_sync('login', '');"
    fi

script:
  - ./script/test

deploy:
  provider: script
  script: ./script/publish
  on:
    all_branches: true
    tags: true
